### ISSUE TITLE
Not all users visible

### ISSUE THREAD

**Issue by geyerbri** [matrix-msu/kora#725] opened 2020-03-17 05:57 UTC
**Describe the bug**
When logged in as admin and viewing "User Management", the interface is only displaying the most recent user to have been activated for a given first name.

**To Reproduce**
1. Sign up a new user with some first name (e.g. Brian) and complete the activation process.
2. Sign up another new user with the same first name and complete the activation process.
3. Log into admin account and navigate to "User Management"
4. See error: only the most recently-activated user with that first name will be visible.

**Expected behavior**
I would expect every user to be listed on "User Management," whether or not their first names are the same.

**Screenshots**
N/A (unless requested?)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Opera
 - Version 67

**Smartphone (please complete the following information):**
N/A

**Additional context**
N/A

**Comment by geyerbri** [comment] 2020-03-17 05:58
This error is confirmed in Firefox Version 72 as well.

**Comment by fritosxii** [comment] 2020-03-17 12:26
That is the weirdest bug, but I was able to reproduce. Working on a fix

**Comment by fritosxii** [comment] 2020-03-17 12:28
Seems to have to do with the sorting algorithm. When sorting in an A-Z fashion, duplicate first names are not included. When sorting by Oldest/Newest all users are present.

**Comment by fritosxii** [comment] 2020-03-17 12:40
Turns out that Z-A sorting was just straight up not working as well. So fixing that along with the duplicate name issue

**Comment by fritosxii** [comment] 2020-03-17 12:46
Issue fixed in master. Feel free to pull in the new changes to confirm the fix

**Closed** 2020-03-17 12:45 UTC
Labels: Bug, Hybrid, Urgent
